<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>QuerySpec.Samples.Migration.CacheStore</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\QuerySpec.Core\QuerySpec.Core.csproj" />
  </ItemGroup>

</Project>
